version: 0.0
os: linux
files:
  - source: API/
    destination: /var/www/api  # Adjust the path as needed
  - source: RMD/
    destination: /var/www/rmd  # Adjust the path as needed
  - source: instantclient_23_5/
    destination: /var/www/instantclient_23_5
hooks:
  ApplicationInstall:
    - location: scripts/install_api_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/install_expo_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_api.sh
      timeout: 300
      runas: root
    - location: scripts/start_expo.sh
      timeout: 300
      runas: root
