version: 0.0
os: linux
files:
  - source: API/
    destination: /var/www/api  # Adjust the path as needed
  - source: RMD/
    destination: /var/www/rmd
hooks:
  ApplicationInstall:
    - location: scripts/install_api_dependencies.sh
      timeout: 300
      runas: root
