version: 0.2
phases:
  install:
    commands:
      - npm install -g expo-cli
      - cd API && npm install
      - cd ../RMD && npm install
  build:
    commands:
      - cd API && npm run build
      - cd ../RMD && npx expo export:web  # Use this for building the web app for deployment
  post_build:
    commands:
      - echo "API and Expo projects built successfully"
artifacts:
  files:
    - API/**/*  # Adjust as needed to include built files
    - RMD/**/*  # Adjust as needed to include built files
