version: 0.2
phases:
  install:
    commands:
      - echo "Navigating to API directory and printing current directory"
      - cd API && pwd && npm install
      - echo "Unzipping Oracle Instant Client from local source"
      - unzip instantclient-basiclite-windows.zip
      - echo "installing Oracle Client"
      - mkdir -p /opt/oracle
      - mv instantclient_23_5 /opt/oracle/instantclient
      - export LD_LIBRARY_PATH=/opt/oracle/instantclient:$LD_LIBRARY_PATH
      - echo "Navigating to RMD directory and printing current directory"
      - cd ../RMD && pwd && npm install
  build:
    commands:
      - echo "Building the API and printing current directory"
      - cd  ../API && pwd && npm run build
      - echo "Building the RMD Expo project and printing current directory"
      - cd  ../RMD && pwd && npx expo export:web

  post_build:
    commands:
      - echo "API and Expo projects built successfully"
artifacts:
  files:
    - API/**/*  # Adjust as needed to include built files
    - RMD/**/*  # Adjust as needed to include built files
