version: 0.2

phases:
  install:
    commands:
      - echo "Setting LD_LIBRARY_PATH for Oracle Instant Client"
      - echo "Verifying LD_LIBRARY_PATH"
      - echo $LD_LIBRARY_PATH
      - export LD_LIBRARY_PATH=$CODEBUILD_SRC_DIR/instantclient_23_5
      - echo "Verifying LD_LIBRARY_PATH"
      - echo $LD_LIBRARY_PATH
      - cd $CODEBUILD_SRC_DIR/API && npm install
  build:
    commands:
      - echo "Building the project"
      - cd $CODEBUILD_SRC_DIR/API && npm run build
  post_build:
    commands:
      - echo "Build phase completed"
