version: 0.2
phases:
  install:
    commands:
      - echo "Navigating to API directory and printing current directory"
      - cd API && pwd && npm install
      - echo "Navigating to RMD directory and printing current directory"
      - cd ../RMD && pwd && npm install
  build:
    commands:
      - echo "Building the API and printing current directory"
      - cd  $CODEBUILD_SRC_DIR/API && pwd && npm run build
      - echo "Building the RMD Expo project and printing current directory"
      - cd  $CODEBUILD_SRC_DIR/RMD && pwd && npx expo export:web

  post_build:
    commands:
      - echo "API and Expo projects built successfully"
artifacts:
  files:
    - API/**/*  # Adjust as needed to include built files
    - RMD/**/*  # Adjust as needed to include built files
